version: '3.6'

services:
  database:
    container_name: mysql
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: backend
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  strapi:
    container_name: strapi
    image: project_strapi
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=backend
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 1337:1337
    expose:
      - 1337
    volumes:
      - ./app:/srv/app
    depends_on:
      - database
    command: ["./wait-for", "database:3306", "--", "npm", "run", "start"]

  nuxt: 
    container_name: nuxt
    image: project_nuxt
    environment:
      - HOST=0.0.0.0
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=5000
      - STRAPI_URL=http://strapi:1337
    ports:
      - "80:5000"
    depends_on:
      - strapi
    command: ["npm", "start"]